### PR TITLE
Work not only in the public schema

### PR DESCRIPTION
**Pull request by vgarvardt**
Currently `public` schema is hardcoded that prevents some functionality from working correctly when non-publis schema is being used.

### CODE REVIEW

**Comment by lucasmdrs** [comment]
@vgarvardt please update with master when you have the time :pray:

**Comment by vgarvardt** [comment]
@lucasmdrs rebased

**Comment by lucasmdrs** [comment]
the tests seem to be a bit flaky, I'll take a look at that later :slightly_frowning_face:

**Comment by vgarvardt** [comment]
It seems that unit test is failing due to some hardcoded timing condition.

**Comment by vgarvardt** [comment]
Tried to reproduce the problem locally, but all the 50 runs I did were successful.

**Comment by lucasmdrs** [comment]
I managed to reproduce the case locally, decided to fix by changing the way the assertions are being made
tried not to impact the exposed API too  #78

**Comment by vgarvardt** [comment]
Cool! Will rebase my branch after https://github.com/hellofresh/goengine/pull/78 is merged.

**Comment by vgarvardt** [comment]
rebased

**Review by lucasmdrs — APPROVED** [review]

**Comment by vgarvardt** [comment]
@lucasmdrs can you pls release new version with the fixed and updates lately merged

**Pull request merged**
