### PR TITLE
Minor code cleanup and typos fix

### PR DESCRIPTION
**Pull request by vgarvardt**
Fixed some typos and cleaned up some tests.

### CODE REVIEW

**Review by lucasmdrs — COMMENTED** [review]
@vgarvardt could you please include the following import to the `mocks.go`:
```golang
_ "github.com/golang/mock/mockgen/model"
```

and also tidy up the module :slightly_smiling_face:

**Comment by vgarvardt** [comment]
> tidy up the module

Done

> include the following import

What for? Everything inside `github.com/golang/mock/mockgen/...` related to the binary that is being installed and used a binary, generated mocks should not require anything from this package

**Comment by vgarvardt** [comment]
True this, reproduced and fixed.

**Review by lucasmdrs — APPROVED** [review]
Thank you! :rocket:

**Pull request merged**
